apiVersion: v1
kind: Service
metadata:
  name: {{ include "vstsagent.fullname" . }}
  labels:
{{ include "vstsagent.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      name: web
      protocol: TCP
      targetPort: 80
    - port: 8080
      name: web2
      protocol: TCP
      targetPort: 8080
    - port: 443
      name: secureweb
      protocol: TCP
      targetPort: 443
  selector:
    app.kubernetes.io/name: {{ include "vstsagent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}