name: Agent-$(Date:yyyyMMdd).$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master
    - dev

variables:
  - group: ado-kv
  - group: ado-config
  - group: tapm

stages: 
  - stage: dev
    displayName: dev  
    jobs: 
    - job: setup
      displayName: setup
      pool:
        vmImage: 'ubuntu-16.04'
      steps: 
      - template: templates/setup.yml
        parameters:
          env: $(ADOENV)
          azure_sub: $(azure_sub)
          name: $(ADONAME)
          location: ${location}
          ARMCLIENTID: $(armclientid)
          ARMCLIENTSECRET: $(armclientsecret)
    - job: plan
      displayName: plan
      dependsOn: setup
      pool:
        vmImage: 'ubuntu-16.04'
      steps: 
      - template: templates/plan.yml
        parameters:
          env: $(ADOENV)
          azure_sub: $(azure_sub)
          name: $(ADONAME)
          ARMCLIENTID: $(armclientid)
          ARMCLIENTSECRET: $(armclientsecret)
    - deployment: apply
      displayName: apply
      environment: dev
      pool:
        vmImage: 'ubuntu-16.04'
      dependsOn: plan
      strategy:
        runOnce:
          deploy:
            steps:
              - template: templates/apply.yml
                parameters: 
                  env: $(ADOENV)
                  azure_sub: $(azure_sub)
                  name: $(ADONAME)
                  ARMCLIENTID: $(armclientid)
                  ARMCLIENTSECRET: $(armclientsecret)
                  ADOTOKEN: $(ADO-TOKEN)
                  ADOPOOL: $(ADO-POOL)
                  ADOORG: $(ADO-ORG)