replicaCount: 3
image:
  repository: gambtho/vstslinux
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
azp:
  url: "replaceme"
  token: "replaceme"
  pool: "replaceme"
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt
  tls:
    - secretName: tls-secret
      hosts:
        - devopsagent.acs
resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
 
